### ISSUE TITLE
Add the target-artifact of pom.xml to load path with LockJar.load

### ISSUE THREAD

**Issue by Hachmaninow** [mguymon/lock_jar#17]
We are using lock_jar in several mixed-language java-jruby-projects. In such a project we use the pom instruction in the Jarfile and lock_jar manages to add all the dependencies to the load path when we call Lockjar.load. Unfortunately the classes contained directly in the java-part of this project are not added to the load path and are thus not available from the ruby code.

Are we missing something or is this a conceptual limitation of lock_jar we have to deal with manually?

**Comment by mguymon** [comment]
There is a bit of a gap in using a pom in a Jarfile. You can reference a pom in the Jarfile , for example - `pom ext/pom.xml`

This will load all the dependencies for the pom. Unfortunately it does not load jar for the actual pom, which makes it almost useful. LockJar expects to be able to resolve deps from a Maven repository. A pom project will have its package installed in the `target` dir normally. For it to work, there will need to be a contract of sort sort that a local pom will be packaged at an expected place.
