### ISSUE TITLE
Merging transitive jar-dependencies of several gem-dependencies without using lock_jar-bundler integration

### ISSUE THREAD

**Issue by Hachmaninow** [mguymon/lock_jar#18]
Using the bundler integration lock_jar very helpfully scans all gems in the current bundle to find Jarfiles in order to merge transitive dependencies. Because of several issues we decided to abandon the bundler integration of lock_jar. Unfortunately there does not seem to be a way to specify gem-dependencies in the Jarfile to achieve the same effect as when using the bundler integration.

Are we missing something?

**Comment by mguymon** [comment]
I ended up keeping support directly in LockJar - https://github.com/mguymon/lock_jar/blob/master/README.md#bundler-integration
