### ISSUE TITLE
--quiet flag ?

### ISSUE THREAD

**Issue by grosser** [mguymon/lock_jar#23]
getting a lot of output from install, what do you think about adding a --quiet flag to reduce the noise level a bit ? :)

@mguymon

**Comment by mguymon** [comment]
Yeah, Naether is super chatty, it makes sense to have it chill out by default. I will tinker around with some quiet and verbose flags.

**Comment by mguymon** [comment]
I squashed the output of Naether to warn log level by default. A new verbose option (-v, --verbose) switches the level backing to info. Released as lock_jar 0.10.3.

**Comment by grosser** [comment]
thx, much cleaner now :)
