### ISSUE TITLE
Gem install fails

### ISSUE THREAD

**Issue by camertron** [mguymon/lock_jar#31]
```
Building native extensions.  This could take a while...
ERROR:  Error installing lock_jar:
	ERROR: Failed to build gem native extension.

    jrake RUBYARCHDIR=/Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java/lib RUBYLIBDIR=/Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java/lib
/bin/sh: jrake: command not found


Gem files will remain installed in /Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java for inspection.
Results logged to /Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java/./gem_make.out
```

Using JRuby v1.7.20, JDK 8

**Comment by camertron** [comment]
For what it's worth, seems to work with jruby 1.7.15

**Comment by mguymon** [comment]
So the naether gem has a Rakefile extension that is run when it is installed. Seems like it is trying to use jrake to do the Rake task:

> /bin/sh: jrake: command not found

**Comment by mguymon** [comment]
@camertron Can you run the task that failed with `rake` (dropping the j)?

    rake RUBYARCHDIR=/Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java/lib RUBYLIBDIR=/Users/cameron/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/naether-0.15.0-java/lib

**Comment by camertron** [comment]
Hey @mguymon sorry for the delay. Unfortunately I decided to abandon jruby 1.7.20 and stay with 1.7.15, so this issue isn't on my radar anymore. Thanks for replying and for the discussion, hopefully it helps others with the same issue.

**Comment by mguymon** [comment]
No worries, give a shout if you have any troubles.
